/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BotRouteImport } from './routes/bot'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MpesaWithdrawRouteImport } from './routes/mpesa.withdraw'
import { Route as MpesaDepositRouteImport } from './routes/mpesa.deposit'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWebhooksCloudpayRouteImport } from './routes/api/public/webhooks/cloudpay'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BotRoute = BotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MpesaWithdrawRoute = MpesaWithdrawRouteImport.update({
  id: '/mpesa/withdraw',
  path: '/mpesa/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const MpesaDepositRoute = MpesaDepositRouteImport.update({
  id: '/mpesa/deposit',
  path: '/mpesa/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksCloudpayRoute =
  ApiPublicWebhooksCloudpayRouteImport.update({
    id: '/api/public/webhooks/cloudpay',
    path: '/api/public/webhooks/cloudpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bot': typeof BotRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/markets': typeof MarketsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/withdraw': typeof WithdrawRoute
  '/mpesa/deposit': typeof MpesaDepositRoute
  '/mpesa/withdraw': typeof MpesaWithdrawRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/api/public/webhooks/cloudpay': typeof ApiPublicWebhooksCloudpayRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bot': typeof BotRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/markets': typeof MarketsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/withdraw': typeof WithdrawRoute
  '/mpesa/deposit': typeof MpesaDepositRoute
  '/mpesa/withdraw': typeof MpesaWithdrawRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/api/public/webhooks/cloudpay': typeof ApiPublicWebhooksCloudpayRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bot': typeof BotRoute
  '/dashboard': typeof DashboardRoute
  '/deposit': typeof DepositRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/markets': typeof MarketsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/withdraw': typeof WithdrawRoute
  '/mpesa/deposit': typeof MpesaDepositRoute
  '/mpesa/withdraw': typeof MpesaWithdrawRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/api/public/webhooks/cloudpay': typeof ApiPublicWebhooksCloudpayRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bot'
    | '/dashboard'
    | '/deposit'
    | '/login'
    | '/logs'
    | '/markets'
    | '/profile'
    | '/signup'
    | '/verify'
    | '/withdraw'
    | '/mpesa/deposit'
    | '/mpesa/withdraw'
    | '/lovable/email/events'
    | '/api/public/webhooks/cloudpay'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bot'
    | '/dashboard'
    | '/deposit'
    | '/login'
    | '/logs'
    | '/markets'
    | '/profile'
    | '/signup'
    | '/verify'
    | '/withdraw'
    | '/mpesa/deposit'
    | '/mpesa/withdraw'
    | '/lovable/email/events'
    | '/api/public/webhooks/cloudpay'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bot'
    | '/dashboard'
    | '/deposit'
    | '/login'
    | '/logs'
    | '/markets'
    | '/profile'
    | '/signup'
    | '/verify'
    | '/withdraw'
    | '/mpesa/deposit'
    | '/mpesa/withdraw'
    | '/lovable/email/events'
    | '/api/public/webhooks/cloudpay'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BotRoute: typeof BotRoute
  DashboardRoute: typeof DashboardRoute
  DepositRoute: typeof DepositRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MarketsRoute: typeof MarketsRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  WithdrawRoute: typeof WithdrawRoute
  MpesaDepositRoute: typeof MpesaDepositRoute
  MpesaWithdrawRoute: typeof MpesaWithdrawRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  ApiPublicWebhooksCloudpayRoute: typeof ApiPublicWebhooksCloudpayRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot': {
      id: '/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof BotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mpesa/withdraw': {
      id: '/mpesa/withdraw'
      path: '/mpesa/withdraw'
      fullPath: '/mpesa/withdraw'
      preLoaderRoute: typeof MpesaWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mpesa/deposit': {
      id: '/mpesa/deposit'
      path: '/mpesa/deposit'
      fullPath: '/mpesa/deposit'
      preLoaderRoute: typeof MpesaDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/cloudpay': {
      id: '/api/public/webhooks/cloudpay'
      path: '/api/public/webhooks/cloudpay'
      fullPath: '/api/public/webhooks/cloudpay'
      preLoaderRoute: typeof ApiPublicWebhooksCloudpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BotRoute: BotRoute,
  DashboardRoute: DashboardRoute,
  DepositRoute: DepositRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MarketsRoute: MarketsRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  WithdrawRoute: WithdrawRoute,
  MpesaDepositRoute: MpesaDepositRoute,
  MpesaWithdrawRoute: MpesaWithdrawRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  ApiPublicWebhooksCloudpayRoute: ApiPublicWebhooksCloudpayRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
